# Generated by Django 3.1.2 on 2020-10-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=1)),
                ('item', models.CharField(default='', max_length=70)),
                ('calorie', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
